### ISSUE TITLE
BringList-Module doesn't appear on MM

### ISSUE THREAD

**Issue by Kuhlemann** [rseidt/MMM-bringList#1]
I get every other module I need working, but this one does not show anything on my MagicMirror (not even an error). It just got updated a month ago, so it should not be a problem of the module being depricated.

**Comment by BoraSchninsky** [comment]
yes.. no function... on my mirror!!!!

**Comment by rseidt** [comment]
I'm running it on my mirror without issues for some months now.
The module should generate very verbous error log entries into the log console of mm. Can you check those on your raspberry and share? I suppose some authentication issues.
Anyway I'll see if I can add verbous errors also to the frontend in case of authentication issues, misconfigurations or timing problems as soon as I find some time.

**Comment by Robi1010MD** [comment]
Hello,
 same problem here:  I recently installed the module, but my list is not displayed. I use the latest version of the MM.

The log file gave me this:

`TypeError: Cannot read property 'listId' of undefined
    at /home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:143:38
    at /home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:132:25
    at Request._callback (/home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:52:17)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-bringList/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-bringList/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-bringList/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
`

Thanks for your help.

**Comment by rseidt** [comment]
> Hello,
> same problem here: I recently installed the module, but my list is not displayed. I use the latest version of the MM.
> 
> The log file gave me this:
> 
> `TypeError: Cannot read property 'listId' of undefined at /home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:143:38 at /home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:132:25 at Request._callback (/home/pi/MagicMirror/modules/MMM-bringList/bring-profile.js:52:17) at Request.self.callback (/home/pi/MagicMirror/modules/MMM-bringList/node_modules/request/request.js:185:22) at Request.emit (events.js:182:13) at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-bringList/node_modules/request/request.js:1161:10) at Request.emit (events.js:182:13) at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-bringList/node_modules/request/request.js:1083:12) at Object.onceWrapper (events.js:273:13) at IncomingMessage.emit (events.js:187:15) `
> 
> Thanks for your help.

Thanks for the Error Log. I checked the location and it is the place where the lists inside your account are fetched from the bring server and the list names are compared with the name inside your configuration. I added some more verbous error messages in this area. So you can do a git pull to get Version 1.0.3
-> Make sure the list name you entered in your configuration matches the exact name in your Bring Web Portal. The configuration is case sensitive. If you have spaces or special characters in your list name please create a new list in your account without spaces and special Characters in the name and retry. If this doesn't help please reconsider the log of the error using v1.0.3

If this helps solving the issue i'd be glad if ou let me know here.

**Comment by fusenigk** [comment]
you must add the position in the config file where the module should be shown:

position: "top_left",
module: 'MMM-bringList',

**Comment by rseidt** [comment]
Thank you, I added position to the samples in the documentation

**Comment by Kuhlemann** [comment]
Great, now it work!
Just another tip: To get a headline (as in your example screen), you have to add

>         {
>             module: 'MMM-bringList',
>             position: 'top_left',
>             header: 'Einkaufsliste',
>             config: {
>             ...
